require: rubocop-rspec

AllCops:
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'

# Ruby 3.0: curly braces around last argument has meaning
# See: https://github.com/rubocop/rubocop/issues/7641
Style/BracesAroundHashParameters:
  Enabled: false

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

RSpec/ExpectInHook:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - cloudenvoy.gemspec
    - lib/tasks/**/*
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/MessageSpies:
  Enabled: false