require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 160

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - cloudenvoy.gemspec
    - lib/tasks/**/*
    - 'spec/**/*'

Metrics/ParameterLists:
  CountKeywordArgs: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/EmptyLineAfterHook:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Style/Documentation:
  Exclude:
    - 'examples/**/*'
    - 'spec/**/*'